# Generated by Django 3.0.7 on 2020-06-24 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prekyba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pardavejas',
            name='pavad',
            field=models.CharField(max_length=30, null=True, verbose_name='Pardavejo Pavadinimas'),
        ),
        migrations.AlterField(
            model_name='preke',
            name='pavadinimas',
            field=models.CharField(max_length=26, verbose_name='Pavadinimas'),
        ),
        migrations.AlterField(
            model_name='sandelys',
            name='prekes_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prekyba.Preke', verbose_name='Preke'),
        ),
    ]
