# Generated by Django 3.0.7 on 2020-06-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prekyba', '0004_auto_20200626_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymas',
            name='perkamas_kiekis',
            field=models.IntegerField(null=True, verbose_name='Perkamas kiekis'),
        ),
    ]
